### ISSUE TITLE
My first issue

### ISSUE THREAD

**Issue by dirkzeuss** [environmentalinformatics-marburg/distribution_digitizer_students#1]
let's make it work

**Comment by Jan-Niklas-Tripp** [comment]
Problem with loading Conda in R-Studio: 

I had already installed Python and got following error in the consol: 

   No non-system installation of Python could be found.
   Would you like to download and install Miniconda?
   Miniconda is an open source environment management system for Python.
   See https://docs.conda.io/en/latest/miniconda.html for more details.

   Would you like to install Miniconda? [Y/n]: 

Hitting Y ended in an error saying: cannot install Miniconda into a path containing spaces

Solution for this problem was entering: n

**Comment by dirkzeuss** [comment]
Please open a new issue for this. Here it is just a comment to an already existing issue.
