### ISSUE TITLE
Possible Improvement

### ISSUE THREAD

**Issue by LeanderHeyer** [environmentalinformatics-marburg/distribution_digitizer_students#2]
The App worked quite well for me after fixing some Errors at the start. I got the same missing cv2 Error at the beginning which was easily fixed by deleting your # sign in front of the already existing line for loading it in.

I also noticed that the script produced many identical images from the same map and I couldn't fix it.

A strange error that occurred to me was after I ran through all the steps and deleted the detected images in the output folder.
The next time I pressed on start map detection it would detect the maps but also match them at the same time.

In the end, the georeferenced maps were quite good after opening them in QGIS.

**Comment by VenkateshMadhuvanthi** [comment]
Thank you very much for the feedback, Leander. The first error might be because of package installation. Since most of them had the package OpenCV already, I added # or commented on the line. The same maps are produced because of the bugs in the program, this will be resolved soon. Deleting the output files before executing all the steps is not recommended as the input of all the modules depends on the input from the previous modules. This could be the reason behind the error.
