### ISSUE TITLE
Error in py_call_impl

### ISSUE THREAD

**Issue by haseeb17** [environmentalinformatics-marburg/distribution_digitizer_students#3]
![error1](https://user-images.githubusercontent.com/32012032/124577904-26453680-de67-11eb-99dc-3c61539801d9.png)
![gcp-view](https://user-images.githubusercontent.com/32012032/124577936-2d6c4480-de67-11eb-9482-0dc30c6f2801.png)
Hi there, I have pasted my ground control points in the given folder geopoints. after running all the buttons I got error in the last button for geo-reference. I got error ( Warning: Error in py_call_impl: KeyError: "None of [Index(['mapX', 'mapY', 'pixelX', 'pixelY', 'enable', 'dX', 'dY', 'residual'], dtype='object')] are in the [columns]" )
  [No stack trace available]

And in the output folder name georeferencing is empty. I have attached my gcp file view that I got from Qgis.

Kind regards,
Haseeb.

**Comment by Jan-Niklas-Tripp** [comment]
Hi Haseeb,

i got the same problem. You have to delete the part before mapX,..., residual. After that save it and close it otherwise you will get the same error because you use the file and the app will shutdown.

An example how your file should look like!

![Beispiel](https://user-images.githubusercontent.com/82509578/124667209-603a2b00-deaf-11eb-88f2-e6a496dd7f6b.PNG)


Greetings,
Jan

**Comment by haseeb17** [comment]
Hi Jan,
              Thank you so much for your help. Yes it works now.

Kind Regards,
Haseeb
